// Generated by CoffeeScript 2.0.2
(function() {
  var Conrand;

  Conrand = (function() {
    class Conrand {
      constructor() {
        this.tick = this.tick.bind(this);
        this.createCanvas();
        this.seed();
        this.tick();
      }

      createCanvas() {
        this.canvas = document.createElement('canvas');
        document.body.appendChild(this.canvas);
        this.canvas.height = this.canvasheight;
        this.canvas.width = this.canvaswidth;
        return this.drawingContext = this.canvas.getContext('2d');
      }

      seed() {
        var i, node, ref, results;
        this.nodeArray = [];
        results = [];
        for (node = i = 0, ref = this.initialnodes; 0 <= ref ? i < ref : i > ref; node = 0 <= ref ? ++i : --i) {
          results.push(this.nodeArray[node] = this.createSeedCircle());
        }
        return results;
      }

      createSeedCircle() {
        return this.createCircle(this.canvas.width * Math.random(), this.canvas.height * Math.random(), 2);
      }

      createCircle(x, y, r) {
        return {
          xPos: x,
          yPos: y,
          radius: r,
          alive: true
        };
      }

      tick() {
        this.evolve();
        this.cull();
        this.draw();
        return setTimeout(this.tick, this.tickLength);
      }

      evolve() {
        var i, len, neighbors, newArray, node;
        newArray = this.nodeArray;
        for (i = 0, len = newArray.length; i < len; i++) {
          node = newArray[i];
          neighbors = this.getNeighbors(node, newArray, this.adjacentDistance);
          if (neighbors.length === 2) {
            this.reflectTriangle(node, neighbors);
          }
          if (neighbors.length === 1) {
            this.buildTriangle(node, neighbors[0], newArray);
          }
          this.vibrate(node, this.vibration);
        }
        return this.nodeArray = newArray;
      }

      cull() {
        var i, index, len, neighbors, newArray, node;
        newArray = this.nodeArray;
        for (i = 0, len = newArray.length; i < len; i++) {
          node = newArray[i];
          neighbors = this.getNeighbors(node, newArray, this.adjacentDistance);
          if (neighbors.length === 0) {
            if (Math.random() < this.isolationDeadliness) {
              node.alive = false;
            }
          }
          if (neighbors.length > this.maximumNeighbors) {
            if (Math.random() < this.maximumNeighbors) {
              node.alive = false;
            }
          }
        }
        index = newArray.length - 1;
        while (index >= 0) {
          if (newArray[index].alive === false) {
            newArray.splice(index, 1);
            index--;
          }
          index--;
        }
        return this.nodeArray = newArray;
      }

      getDistance(a, b) {
        var sumOfSquares, xdiff, ydiff;
        xdiff = b.xPos - a.xPos;
        ydiff = b.yPos - a.yPos;
        sumOfSquares = Math.pow(xdiff, 2) + Math.pow(ydiff, 2);
        return Math.sqrt(sumOfSquares);
      }

      getNeighbors(node, array, distance) {
        var d, i, len, neighbors, x;
        neighbors = [];
        for (i = 0, len = array.length; i < len; i++) {
          x = array[i];
          d = this.getDistance(node, x);
          if (d < distance && d > 0) {
            neighbors.push(x);
          }
        }
        return neighbors;
      }

      vibrate(node, factor) {
        node.xPos = node.xPos + ((Math.random() - 0.5) * 2 * factor);
        node.yPos = node.yPos + ((Math.random() - 0.5) * 2 * factor);
        return this.rectifyNode(node);
      }

      rectifyNode(node) {
        if (node.xPos > this.canvas.width) {
          node.xPos = this.canvas.width;
        }
        if (node.yPos > this.canvas.height) {
          node.yPos = this.canvas.height;
        }
        if (node.xPos < 0) {
          node.xPos = 0;
        }
        if (node.yPos < 0) {
          return node.yPos = 0;
        }
      }

      buildTriangle(a, b, array) {
        var newCircle, newX, newY, theta;
        theta = 60;
        if (Math.random() < 0.5) {
          theta = 300;
        }
        newX = Math.cos(theta) * (a.xPos - b.xPos) - Math.sin(theta) * (a.yPos - b.yPos) + b.xPos;
        newY = Math.sin(theta) * (a.xPos - b.xPos) + Math.cos(theta) * (a.yPos - b.yPos) + b.yPos;
        newCircle = this.createCircle(newX, newY, a.radius);
        this.rectifyNode(newCircle);
        return array.push(newCircle);
      }

      reflectTriangle(node, neighbors) {
        var a, b, d1, d2, theta;
        d1 = this.getDistance(node, neighbors[0]);
        d2 = this.getDistance(node, neighbors[1]);
        if (d1 > d2) {
          a = neighbors[1];
          b = neighbors[0];
        } else {
          a = neighbors[0];
          b = neighbors[1];
        }
        theta = 90 - Math.atan(d1 / d2) * (180 / Math.PI);
        node.xPos = Math.cos(theta) * (a.xPos - b.xPos) - Math.sin(theta) * (a.yPos - b.yPos) + b.xPos;
        node.yPos = Math.sin(theta) * (a.xPos - b.xPos) + Math.cos(theta) * (a.yPos - b.yPos) + b.yPos;
        return this.rectifyNode(node);
      }

      draw() {
        var i, j, len, len1, node, ref, ref1, results;
        this.drawingContext.clearRect(0, 0, this.canvas.width, this.canvas.height);
        ref = this.nodeArray;
        for (i = 0, len = ref.length; i < len; i++) {
          node = ref[i];
          if (node.alive === true) {
            this.drawConnections(node, this.nodeArray, this.adjacentDistance);
          }
        }
        ref1 = this.nodeArray;
        results = [];
        for (j = 0, len1 = ref1.length; j < len1; j++) {
          node = ref1[j];
          if (node.alive === true) {
            results.push(this.drawCircle(node));
          } else {
            results.push(void 0);
          }
        }
        return results;
      }

      drawConnections(node, array, distance) {
        var context, i, len, neighbors, results, x;
        neighbors = this.getNeighbors(node, array, distance);
        context = this.drawingContext;
        context.lineWidth = 1;
        context.strokeStyle = 'rgb(242, 198, 65)';
        results = [];
        for (i = 0, len = neighbors.length; i < len; i++) {
          x = neighbors[i];
          context.beginPath();
          context.moveTo(node.xPos, node.yPos);
          context.lineTo(x.xPos, x.yPos);
          results.push(context.stroke());
        }
        return results;
      }

      drawCircle(circle) {
        if (circle.alive === true) {
          this.drawingContext.fillStyle = 'white';
        } else {
          this.drawingContext.fillStyle = 'grey';
        }
        this.drawingContext.lineWidth = 2;
        this.drawingContext.strokeStyle = 'rgba(242, 198, 65, 0.1)';
        this.drawingContext.beginPath();
        this.drawingContext.arc(circle.xPos, circle.yPos, circle.radius, 0, 2 * Math.PI, false);
        this.drawingContext.fill();
        return this.drawingContext.stroke();
      }

    };

    Conrand.prototype.nodeArray = null;

    Conrand.prototype.canvas = null;

    Conrand.prototype.drawingContext = null;

    //graphics parameters
    Conrand.prototype.canvasheight = 900;

    Conrand.prototype.canvaswidth = 900;

    //game parameters
    Conrand.prototype.tickLength = 150;

    Conrand.prototype.initialnodes = 200;

    Conrand.prototype.isolationDeadliness = 0.5;

    Conrand.prototype.maximumNeighbors = 3;

    Conrand.prototype.overcrowdingDeadliness = 0.5;

    Conrand.prototype.adjacentDistance = 90;

    Conrand.prototype.vibration = 4;

    return Conrand;

  })();

  window.Conrand = Conrand;

}).call(this);
